language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy"
  # - "pypy3"
notifications:
  email: false
install:
  - pip install -r test-requirements.txt
  - python setup.py install
script: "python -m pytest"
